use olist;
-- 1.Total revenue.

SELECT 
    SUM(price) AS total_revenue
FROM
    olist.olist_order_items_dataset;
 
 -- 2.Monthly revenue trend.
 
SELECT 
    YEAR(o.order_purchase_timestamp) AS order_year,
    MONTH(o.order_purchase_timestamp) AS order_month,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM
    olist.orders_dataset o;
 
 -- 3.Find the Top 10 product categories by revenue.
SELECT 
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM
    olist_order_items_dataset oi
        JOIN
    olist_products_dataset p ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 10;
 
 -- 4.Find the Top 10 best-selling products by quantity sold.
SELECT 
    oi.product_id, COUNT(*) AS quantity_sold
FROM
    olist_order_items_dataset oi
GROUP BY product_id
ORDER BY quantity_sold DESC
LIMIT 10;
 
 -- 5.Find the Top 10 sellers by revenue.
SELECT 
    s.seller_id, ROUND(SUM(oi.price), 2) AS total_revenue
FROM
    olist_sellers_dataset s
        JOIN
    olist_order_items_dataset oi ON s.seller_id = oi.seller_id
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;
 
 -- 6.Find the Top 10 customers by total spending.
SELECT 
    c.customer_unique_id,
    ROUND(SUM(op.payment_value), 2) AS total_spending
FROM
    olist_customers_dataset c
        JOIN
    olist_orders_dataset o ON c.customer_id = o.customer_id
        JOIN
    olist_order_payments_dataset op ON o.order_id = op.order_id
GROUP BY customer_unique_id
ORDER BY total_spending DESC
LIMIT 10;
 
 -- 7.Calculate the Average Order Value (AOV).
SELECT 
    ROUND(SUM(op.payment_value), 2) / COUNT(DISTINCT o.order_id) AS avg_order
FROM
    olist_orders_dataset o
        JOIN
    olist_order_payments_dataset op ON o.order_id = op.order_id;
 
 -- 8.Find the average delivery time (in days).
SELECT 
    ROUND(AVG(DATEDIFF(order_delivered_customer_date,
                    order_purchase_timestamp)),
            2) AS avg_delivery_time_day
FROM
    olist_orders_dataset
WHERE
    order_delivered_customer_date IS NOT NULL;
 
 -- 9.Find orders delivered after the estimated delivery date.
SELECT 
    order_id,
    order_delivered_customer_date,
    order_purchase_timestamp,
    order_estimated_delivery_date,
    DATEDIFF(order_delivered_customer_date,
            order_estimated_delivery_date) AS delay_days
FROM
    olist_orders_dataset
WHERE
    order_status = 'delivered'
        AND order_delivered_customer_date > order_estimated_delivery_date
ORDER BY delay_days DESC;

-- 10.Calculate monthly revenue.
SELECT 
    YEAR(o.order_purchase_timestamp) AS order_year,
    MONTH(o.order_purchase_timestamp) AS order_month,
    MONTHNAME(o.order_purchase_timestamp) AS month_name,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM
    olist_orders_dataset o
        JOIN
    olist_order_items_dataset oi ON o.order_id = oi.order_id
GROUP BY YEAR(o.order_purchase_timestamp) , MONTH(o.order_purchase_timestamp) , MONTHNAME(o.order_purchase_timestamp)
ORDER BY YEAR(o.order_purchase_timestamp) , MONTH(o.order_purchase_timestamp);
    
-- 11. Find revenue generated by each payment type.
SELECT 
    payment_type, ROUND(SUM(payment_value), 2) AS total_revenue
FROM
    olist_order_payments_dataset
GROUP BY payment_type
ORDER BY total_revenue DESC;